image: openjdk:8-jdk

variables:
  ANDROID_BUILD_TOOLS: "25.0.2"
  NDK_VERSION: "17c"

before_script:
  - cat /etc/issue
  - uname -a
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget unzip lib32stdc++6 lib32z1 ant ant-optional faketime git tcl libtool automake autoconf gawk libssl-dev make libqt5widgets5

  - cd ..
  - wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
  - chmod +x android-wait-for-emulator
  - wget --quiet --output-document=android-sdk.tgz https://dl.google.com/android/repository/tools_r25.2.5-linux.zip
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - unzip -qq -d $ANDROID_HOME android-sdk.tgz

  - mkdir -p $ANDROID_HOME/licenses || true
  - echo 8933bad161af4178b1185d1a37fbf41ea5269c55 > $ANDROID_HOME/licenses/android-sdk-license
  - echo 79120722343a6f314e0719f863036c702b0e6b2a > $ANDROID_HOME/licenses/android-sdk-preview-license
  - echo 84831b9409646a918e30573bab4c9c91346d8abd > $ANDROID_HOME/licenses/android-sdk-preview-license-d099d938

  - echo y | $ANDROID_HOME/tools/android --silent update sdk --no-ui --all --filter
    android-14,android-25,platform-tools,extra-android-m2repository,build-tools-${ANDROID_BUILD_TOOLS}
  - export PATH=$PATH:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools

  - wget --quiet --output-document=android-ndk.zip https://dl.google.com/android/repository/android-ndk-r${NDK_VERSION}-linux-x86_64.zip
  - unzip -qq android-ndk.zip
  - export ANDROID_NDK_HOME=$PWD/android-ndk-r${NDK_VERSION}

build:
  artifacts:
    name: "${CI_PROJECT_PATH}_${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
      - ${CI_PROJECT_NAME}*.*
    expire_in: 1 week
    when: always
  after_script:
    - echo "Download debug artifacts from https://gitlab.com/${CI_PROJECT_PATH}/-/jobs"
  script:
    - cd $CI_PROJECT_DIR

    # prep for the ./gradlew builds
    - git clean -fdx
    - git reset --hard
    - git submodule foreach --recursive git reset --hard
    - git submodule foreach --recursive git clean -fdx
    - git submodule sync --recursive
    - git submodule foreach --recursive git submodule sync
    - git submodule update --init --recursive
    - ./gradlew build
    - sed -i -e 's,textReport .*,textReport true,' build.gradle

    - ./make-release-build
